channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - apptools=4.4.0=py36_1002
  - asn1crypto=0.24.0=py36_1003
  - awscli=1.16.226=py36_0
  - boto3=1.9.216=py_0
  - botocore=1.12.216=py_0
  - bzip2=1.0.8=h516909a_0
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3=py36h8022711_0
  - cloudpickle=1.2.1=py_0
  - colorama=0.3.9=py_1
  - configobj=5.0.6=py_0
  - cryptography=2.7=py36h72c5cf5_0
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_1
  - cython=0.29.13=py36he1b5a44_0
  - cytoolz=0.10.0=py36h516909a_0
  - dask-core=2.3.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - docutils=0.15.2=py36_0
  - envisage=4.7.2=py_0
  - expat=2.2.5=he1b5a44_1003
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - future=0.17.1=py36_1000
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5=1.10.5=nompi_h3c11f04_1103
  - icu=64.2=he1b5a44_1
  - idna=2.8=py36_1000
  - imageio=2.5.0=py36_0
  - jmespath=0.9.4=py_0
  - jpeg=9c=h14c3975_1001
  - jsoncpp=1.8.4=hc9558a2_1001
  - kiwisolver=1.1.0=py36hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libcurl=7.65.3=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=12_openblas
  - libnetcdf=4.6.2=h056eaf5_1002
  - libopenblas=0.3.7=h6e990d7_1
  - libpng=1.6.37=hed695b0_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hee79883_5
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.1.1=py36_1
  - matplotlib-base=3.1.1=py36he7580a8_1
  - mayavi=4.7.1=py36h7eb8c7e_2
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.3=py_0
  - numpy=1.17.0=py36h95a1406_0
  - olefile=0.46=py_0
  - openssl=1.1.1c=h516909a_0
  - pandas=0.25.1=py36hb3f55d8_0
  - pcre=8.41=hf484d3e_1003
  - pillow=6.1.0=py36h6b7be26_1
  - pip=19.2.3=py36_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyamg=4.0.0=py36h9de70de_1001
  - pyasn1=0.4.6=py_0
  - pycparser=2.19=py36_1
  - pyface=6.1.2=py_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36hcca6a23_2
  - pysocks=1.7.0=py36_0
  - python=3.6.7=h357f687_1005
  - python-dateutil=2.8.0=py_0
  - pytz=2019.2=py_0
  - pywavelets=1.0.3=py36hd352d35_1
  - pyyaml=5.1.2=py36h516909a_0
  - qt=5.9.7=h0c104cb_3
  - readline=8.0=hf8c457e_0
  - rsa=3.4.2=py_1
  - s3transfer=0.2.1=py36_0
  - scikit-image=0.15.0=py36hb3f55d8_2
  - scipy=1.3.1=py36h921218d_2
  - setuptools=41.2.0=py36_0
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - sqlite=3.29.0=hcee41ef_0
  - tbb=2019.7=hc9558a2_0
  - tk=8.6.9=hed695b0_1002
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h516909a_0
  - traits=5.1.2=py36h516909a_0
  - traitsui=6.1.2=py_0
  - urllib3=1.25.3=py36_0
  - vtk=8.2.0=py36hfdee58b_203
  - wheel=0.33.6=py36_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxt=1.2.0=h516909a_0
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zlib=1.2.11=h516909a_1005
  - zstd=1.4.0=h3b9ef0a_0
  - pip:
    - --extra-index-url https://pypi.fury.io/dd8/
    - "git+https://github.com/LeeKamentsky/python-javabridge.git@c7ccaed43ac7752c4ca361abb04fcb4e9ebdb069"
    - matplotlib-scalebar==0.6.0
    - pyqt5==5.13.0
    - pyqt5-sip==4.19.18
    - python-bioformats==1.1.0
    - simpleitk==1.2.0rc2.dev1162+g2a79d

