channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - apptools=4.5.0=py_0
  - awscli=1.17.14=py36_0
  - boto3=1.11.14=py_0
  - botocore=1.14.14=py_0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36h8022711_0
  - cloudpickle=1.2.2=py_1
  - colorama=0.4.3=py_0
  - configobj=5.0.6=py_0
  - cryptography=2.8=py36h72c5cf5_1
  - curl=7.68.0=hf8cf82a_0
  - cycler=0.10.0=py_2
  - cython=0.29.15=py36he1b5a44_0
  - cytoolz=0.10.1=py36h516909a_0
  - dask-core=2.10.1=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - docutils=0.15.2=py36_0
  - envisage=4.8.0=py_0
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - future=0.18.2=py36_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=py36h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_1
  - gstreamer=1.14.5=h36ae1b5_1
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - idna=2.8=py36_1000
  - imageio=2.6.1=py36_0
  - jdcal=1.4.1=py_0
  - jmespath=0.9.4=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - jsoncpp=1.8.4=hc9558a2_1002
  - kiwisolver=1.1.0=py36hc9558a2_0
  - krb5=1.16.4=h2fd8d38_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.1=default_hde54327_0
  - libcurl=7.68.0=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - libllvm9=9.0.1=hc9558a2_0
  - libnetcdf=4.7.3=nompi_h9f9fd6a_101
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36h250f245_0
  - mayavi=4.7.1=py36h7eb8c7e_2
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.1=py36h95a1406_0
  - olefile=0.46=py_0
  - openjdk=8.0.192=h516909a_1004
  - openpyxl=3.0.3=py_0
  - openssl=1.1.1d=h516909a_0
  - pandas=1.0.1=py36hb3f55d8_0
  - pcre=8.43=he1b5a44_0
  - pillow=7.0.0=py36hefe7db6_0
  - pip=20.0.2=py_2
  - pthread-stubs=0.4=h14c3975_1001
  - pyamg=4.0.0=py36h9de70de_1001
  - pyasn1=0.4.8=py_0
  - pycparser=2.19=py36_1
  - pyface=6.1.2=py_0
  - pygments=2.5.2=py_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.6=py_0
  - pysocks=1.7.1=py36_0
  - python=3.6.7=h357f687_1006
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36hc1659b7_0
  - pyyaml=5.2=py36h516909a_0
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=hf8c457e_0
  - rsa=3.4.2=py_1
  - s3transfer=0.3.3=py36_0
  - scikit-image=0.16.2=py36hb3f55d8_0
  - scikit-learn=0.22.1=py36hcdab131_1
  - scipy=1.4.1=py36h921218d_0
  - setuptools=45.2.0=py36_0
  - six=1.14.0=py36_0
  - sqlite=3.30.1=hcee41ef_0
  - tbb=2019.9=hc9558a2_1
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h516909a_3
  - traits=5.2.0=py36h516909a_0
  - traitsui=6.1.3=py_0
  - urllib3=1.25.7=py36_0
  - vtk=8.2.0=py36h9286700_207
  - wheel=0.34.2=py_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxt=1.2.0=h516909a_0
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.2.2=h516909a_1
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - --extra-index-url https://pypi.fury.io/dd8/
    - javabridge==1.0.18.post16+gc7ccaed
    - matplotlib-scalebar==0.6.1
    - pyqt5==5.14.1
    - pyqt5-sip==12.7.1
    - pyqtwebengine==5.12.1
    - python-bioformats==1.1.0
    - simpleitk==1.2.0rc2.dev1162+g2a79d

